# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/GUI/asciiDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_asciiDialog(object):
    def setupUi(self, asciiDialog):
        asciiDialog.setObjectName("asciiDialog")
        asciiDialog.resize(487, 169)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(asciiDialog.sizePolicy().hasHeightForWidth())
        asciiDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(asciiDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filenameButton = QtWidgets.QPushButton(asciiDialog)
        self.filenameButton.setObjectName("filenameButton")
        self.horizontalLayout.addWidget(self.filenameButton)
        self.filenameLabel = QtWidgets.QLabel(asciiDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filenameLabel.sizePolicy().hasHeightForWidth())
        self.filenameLabel.setSizePolicy(sizePolicy)
        self.filenameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.filenameLabel.setObjectName("filenameLabel")
        self.horizontalLayout.addWidget(self.filenameLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.metadataCheck = QtWidgets.QCheckBox(asciiDialog)
        self.metadataCheck.setChecked(True)
        self.metadataCheck.setObjectName("metadataCheck")
        self.gridLayout.addWidget(self.metadataCheck, 0, 0, 1, 1)
        self.underlineCheck = QtWidgets.QCheckBox(asciiDialog)
        self.underlineCheck.setChecked(True)
        self.underlineCheck.setObjectName("underlineCheck")
        self.gridLayout.addWidget(self.underlineCheck, 0, 1, 1, 1)
        self.kitKeyCheck = QtWidgets.QCheckBox(asciiDialog)
        self.kitKeyCheck.setChecked(True)
        self.kitKeyCheck.setObjectName("kitKeyCheck")
        self.gridLayout.addWidget(self.kitKeyCheck, 2, 0, 1, 1)
        self.omitEmptyCheck = QtWidgets.QCheckBox(asciiDialog)
        self.omitEmptyCheck.setChecked(True)
        self.omitEmptyCheck.setObjectName("omitEmptyCheck")
        self.gridLayout.addWidget(self.omitEmptyCheck, 3, 0, 1, 1)
        self.printCountsCheck = QtWidgets.QCheckBox(asciiDialog)
        self.printCountsCheck.setChecked(True)
        self.printCountsCheck.setObjectName("printCountsCheck")
        self.gridLayout.addWidget(self.printCountsCheck, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.emptyLineAfterSectionCheck = QtWidgets.QCheckBox(asciiDialog)
        self.emptyLineAfterSectionCheck.setChecked(True)
        self.emptyLineAfterSectionCheck.setObjectName("emptyLineAfterSectionCheck")
        self.gridLayout.addWidget(self.emptyLineAfterSectionCheck, 3, 1, 1, 1)
        self.emptyLineBeforeSectionCheck = QtWidgets.QCheckBox(asciiDialog)
        self.emptyLineBeforeSectionCheck.setChecked(True)
        self.emptyLineBeforeSectionCheck.setObjectName("emptyLineBeforeSectionCheck")
        self.gridLayout.addWidget(self.emptyLineBeforeSectionCheck, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(asciiDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(asciiDialog)
        self.buttonBox.accepted.connect(asciiDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(asciiDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(asciiDialog)

    def retranslateUi(self, asciiDialog):
        _translate = QtCore.QCoreApplication.translate
        asciiDialog.setWindowTitle(_translate("asciiDialog", "Export ASCII file"))
        self.filenameButton.setToolTip(_translate("asciiDialog", "Click to select a new filename"))
        self.filenameButton.setText(_translate("asciiDialog", "Filename:"))
        self.filenameLabel.setToolTip(_translate("asciiDialog", "The filename to export this score to"))
        self.filenameLabel.setText(_translate("asciiDialog", "Filename"))
        self.metadataCheck.setToolTip(_translate("asciiDialog", "Export the song information"))
        self.metadataCheck.setText(_translate("asciiDialog", "Song info (Title, artist, etc.)"))
        self.underlineCheck.setToolTip(_translate("asciiDialog", "Underline each section title"))
        self.underlineCheck.setText(_translate("asciiDialog", "Underline section titles with ~ characters"))
        self.kitKeyCheck.setToolTip(_translate("asciiDialog", "Export the drum kit key"))
        self.kitKeyCheck.setText(_translate("asciiDialog", "Drum kit key"))
        self.omitEmptyCheck.setToolTip(_translate("asciiDialog", "Empty lines for unlocked drums are not written to the ASCII tab"))
        self.omitEmptyCheck.setText(_translate("asciiDialog", "Omit empty lines for unlocked drums"))
        self.printCountsCheck.setToolTip(_translate("asciiDialog", "Export the beat count underneath each measure"))
        self.printCountsCheck.setText(_translate("asciiDialog", "Beat count"))
        self.emptyLineAfterSectionCheck.setToolTip(_translate("asciiDialog", "Include a blank line after each section title"))
        self.emptyLineAfterSectionCheck.setText(_translate("asciiDialog", "Empty line after section title"))
        self.emptyLineBeforeSectionCheck.setToolTip(_translate("asciiDialog", "Include a blank line before each section title"))
        self.emptyLineBeforeSectionCheck.setText(_translate("asciiDialog", "Empty line before section title"))
