# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/GUI/alternateRepeatWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import GUI.DrumBurp_rc  # noqa: F401 — registra recursos :/Icons y :/fonts


class Ui_AlternateWidget(object):
    def setupUi(self, AlternateWidget):
        AlternateWidget.setObjectName("AlternateWidget")
        AlternateWidget.resize(273, 24)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AlternateWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startBox = QtWidgets.QSpinBox(AlternateWidget)
        self.startBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startBox.setMinimum(1)
        self.startBox.setMaximum(100000000)
        self.startBox.setObjectName("startBox")
        self.horizontalLayout.addWidget(self.startBox)
        self.endBox = QtWidgets.QSpinBox(AlternateWidget)
        self.endBox.setEnabled(True)
        self.endBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endBox.setReadOnly(False)
        self.endBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.endBox.setMinimum(1)
        self.endBox.setMaximum(10000000)
        self.endBox.setObjectName("endBox")
        self.horizontalLayout.addWidget(self.endBox)
        self.rangeCheck = QtWidgets.QCheckBox(AlternateWidget)
        self.rangeCheck.setChecked(True)
        self.rangeCheck.setObjectName("rangeCheck")
        self.horizontalLayout.addWidget(self.rangeCheck)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.deleteButton = QtWidgets.QPushButton(AlternateWidget)
        self.deleteButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/process-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon)
        self.deleteButton.setFlat(True)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)

        self.retranslateUi(AlternateWidget)
        self.rangeCheck.toggled['bool'].connect(self.endBox.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AlternateWidget)

    def retranslateUi(self, AlternateWidget):
        _translate = QtCore.QCoreApplication.translate
        AlternateWidget.setWindowTitle(_translate("AlternateWidget", "Form"))
        self.startBox.setToolTip(_translate("AlternateWidget", "Repeat number"))
        self.endBox.setToolTip(_translate("AlternateWidget", "Repeat number range end"))
        self.rangeCheck.setToolTip(_translate("AlternateWidget", "Range of repeat numbers?"))
        self.rangeCheck.setText(_translate("AlternateWidget", "Range?"))
        self.deleteButton.setToolTip(_translate("AlternateWidget", "Delete this repeat"))
