# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/GUI/alternateRepeats.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GUI.QtResourceCompat import QPixmap as _CompatQPixmap
QtGui.QPixmap = _CompatQPixmap


class Ui_AlternateDialog(object):
    def setupUi(self, AlternateDialog):
        AlternateDialog.setObjectName("AlternateDialog")
        AlternateDialog.resize(502, 214)
        self.verticalLayout = QtWidgets.QVBoxLayout(AlternateDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(AlternateDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.addButton = QtWidgets.QPushButton(AlternateDialog)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.repeatsFrame = QtWidgets.QScrollArea(AlternateDialog)
        self.repeatsFrame.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.repeatsFrame.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.repeatsFrame.setWidgetResizable(True)
        self.repeatsFrame.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.repeatsFrame.setObjectName("repeatsFrame")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 465, 134))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(9, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.repeatsLayout = QtWidgets.QVBoxLayout()
        self.repeatsLayout.setSpacing(0)
        self.repeatsLayout.setObjectName("repeatsLayout")
        self.verticalLayout_2.addLayout(self.repeatsLayout)
        self.stretchyLayout = QtWidgets.QVBoxLayout()
        self.stretchyLayout.setObjectName("stretchyLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.stretchyLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.stretchyLayout)
        self.repeatsFrame.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.repeatsFrame)
        self.buttonBox = QtWidgets.QDialogButtonBox(AlternateDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AlternateDialog)
        self.buttonBox.accepted.connect(AlternateDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AlternateDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AlternateDialog)

    def retranslateUi(self, AlternateDialog):
        _translate = QtCore.QCoreApplication.translate
        AlternateDialog.setWindowTitle(_translate("AlternateDialog", "Alternate Repeats"))
        self.label.setText(_translate("AlternateDialog", "Enter alternate repeat information:"))
        self.addButton.setToolTip(_translate("AlternateDialog", "Add a new repeat"))
        self.addButton.setText(_translate("AlternateDialog", "Add"))
