# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/GUI/DBComplextCountDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
QtGui.QPixmap = _CompatQPixmap


class Ui_complexCountDialog(object):
    def setupUi(self, complexCountDialog):
        complexCountDialog.setObjectName("complexCountDialog")
        complexCountDialog.resize(322, 251)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(complexCountDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.beatList = QtWidgets.QListWidget(complexCountDialog)
        self.beatList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.beatList.setProperty("showDropIndicator", False)
        self.beatList.setObjectName("beatList")
        self.horizontalLayout_2.addWidget(self.beatList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addButton = QtWidgets.QPushButton(complexCountDialog)
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QPushButton(complexCountDialog)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout.addWidget(self.deleteButton)
        self.label_2 = QtWidgets.QLabel(complexCountDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.countBox = QtWidgets.QComboBox(complexCountDialog)
        self.countBox.setObjectName("countBox")
        self.verticalLayout.addWidget(self.countBox)
        self.label_3 = QtWidgets.QLabel(complexCountDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.numTicksSpinBox = QtWidgets.QSpinBox(complexCountDialog)
        self.numTicksSpinBox.setObjectName("numTicksSpinBox")
        self.verticalLayout.addWidget(self.numTicksSpinBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(complexCountDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previewText = QtWidgets.QLabel(self.groupBox)
        self.previewText.setAutoFillBackground(False)
        self.previewText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.previewText.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.previewText.setAlignment(QtCore.Qt.AlignCenter)
        self.previewText.setWordWrap(True)
        self.previewText.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.previewText.setObjectName("previewText")
        self.horizontalLayout.addWidget(self.previewText)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(complexCountDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(complexCountDialog)
        self.buttonBox.accepted.connect(complexCountDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(complexCountDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(complexCountDialog)

    def retranslateUi(self, complexCountDialog):
        _translate = QtCore.QCoreApplication.translate
        complexCountDialog.setWindowTitle(_translate("complexCountDialog", "Edit Complex Measure Count"))
        self.beatList.setToolTip(_translate("complexCountDialog", "List of beats in the measure count"))
        self.addButton.setToolTip(_translate("complexCountDialog", "Add a new beat at the end of this count"))
        self.addButton.setText(_translate("complexCountDialog", "Add Beat"))
        self.deleteButton.setToolTip(_translate("complexCountDialog", "Delete the currently selected count"))
        self.deleteButton.setText(_translate("complexCountDialog", "Delete Beat"))
        self.label_2.setText(_translate("complexCountDialog", "Count"))
        self.countBox.setToolTip(_translate("complexCountDialog", "Count to use for the current beat"))
        self.label_3.setText(_translate("complexCountDialog", "Ticks"))
        self.numTicksSpinBox.setToolTip(_translate("complexCountDialog", "How many ticks of the count should the current beat use?"))
        self.groupBox.setToolTip(_translate("complexCountDialog", "Preview of the measure count according to the current settings"))
        self.groupBox.setTitle(_translate("complexCountDialog", "Preview"))
        self.previewText.setText(_translate("complexCountDialog", "TextLabel"))
        self.buttonBox.setToolTip(_translate("complexCountDialog", "Reset the count to the original settings"))
