# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/GUI/defaultKitManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DefaulKitManager(object):
    def setupUi(self, DefaulKitManager):
        DefaulKitManager.setObjectName("DefaulKitManager")
        DefaulKitManager.resize(353, 311)
        self.horizontalLayout = QtWidgets.QHBoxLayout(DefaulKitManager)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.defaultKitList = QtWidgets.QListWidget(DefaulKitManager)
        self.defaultKitList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.defaultKitList.setProperty("showDropIndicator", False)
        self.defaultKitList.setObjectName("defaultKitList")
        self.horizontalLayout.addWidget(self.defaultKitList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.saveButton = QtWidgets.QPushButton(DefaulKitManager)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.overwriteButton = QtWidgets.QPushButton(DefaulKitManager)
        self.overwriteButton.setObjectName("overwriteButton")
        self.verticalLayout.addWidget(self.overwriteButton)
        self.deleteButton = QtWidgets.QPushButton(DefaulKitManager)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout.addWidget(self.deleteButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.openButton = QtWidgets.QPushButton(DefaulKitManager)
        self.openButton.setObjectName("openButton")
        self.verticalLayout.addWidget(self.openButton)
        self.cancelButton = QtWidgets.QPushButton(DefaulKitManager)
        self.cancelButton.setObjectName("cancelButton")
        self.verticalLayout.addWidget(self.cancelButton)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(DefaulKitManager)
        self.cancelButton.clicked.connect(DefaulKitManager.reject) # type: ignore
        self.openButton.clicked.connect(DefaulKitManager.accept) # type: ignore
        self.defaultKitList.itemDoubleClicked['QListWidgetItem*'].connect(DefaulKitManager.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DefaulKitManager)
        DefaulKitManager.setTabOrder(self.defaultKitList, self.saveButton)
        DefaulKitManager.setTabOrder(self.saveButton, self.overwriteButton)
        DefaulKitManager.setTabOrder(self.overwriteButton, self.deleteButton)
        DefaulKitManager.setTabOrder(self.deleteButton, self.openButton)
        DefaulKitManager.setTabOrder(self.openButton, self.cancelButton)

    def retranslateUi(self, DefaulKitManager):
        _translate = QtCore.QCoreApplication.translate
        DefaulKitManager.setWindowTitle(_translate("DefaulKitManager", "Default Kit Manager"))
        self.defaultKitList.setToolTip(_translate("DefaulKitManager", "Available default kits"))
        self.defaultKitList.setWhatsThis(_translate("DefaulKitManager", "<html><head/><body><p><span style=\" font-weight:600;\">Default kit list</span></p><p><br/></p><p>Kits listed here can be loaded into the kit editor by double-clicking, or selecting them and clicking the <span style=\" font-style:italic;\">Open</span> button.</p><p><br/></p><p>Kits listed in <span style=\" font-style:italic;\">italics</span> are built into DrumBurp and cannot be overwritten, deleted or renamed.</p></body></html>"))
        self.saveButton.setToolTip(_translate("DefaulKitManager", "Save the current kit as a new default"))
        self.saveButton.setWhatsThis(_translate("DefaulKitManager", "<html><head/><body><p><span style=\" font-weight:600;\">Save a new default kit</span></p><p><br/></p><p>Save the kit currently loaded in the kit editor as a new default. You will be asked a name to save it under, then it will appear in this dialog whenever you run DrumBurp in the future.</p></body></html>"))
        self.saveButton.setText(_translate("DefaulKitManager", "Save New"))
        self.overwriteButton.setToolTip(_translate("DefaulKitManager", "Overwrite this default kit"))
        self.overwriteButton.setWhatsThis(_translate("DefaulKitManager", "<html><head/><body><p><span style=\" font-weight:600;\">Overwrite this default kit</span></p><p><br/></p><p>The currently selected default kit will be overwritten with the kit currently loaded into the kit editor.</p></body></html>"))
        self.overwriteButton.setText(_translate("DefaulKitManager", "Overwrite"))
        self.deleteButton.setToolTip(_translate("DefaulKitManager", "Delete this default kit"))
        self.deleteButton.setWhatsThis(_translate("DefaulKitManager", "<html><head/><body><p><span style=\" font-weight:600;\">Delete this default kit</span></p><p><br/></p><p>Delete this default kit from the default kit list. DrumBurp builtin default kits cannot be deleted.</p></body></html>"))
        self.deleteButton.setText(_translate("DefaulKitManager", "Delete"))
        self.openButton.setToolTip(_translate("DefaulKitManager", "Load this default kit"))
        self.openButton.setWhatsThis(_translate("DefaulKitManager", "<html><head/><body><p><span style=\" font-weight:600;\">Load default kit</span></p><p><br/></p><p>Load the currently selected default kit into the kit editor.</p></body></html>"))
        self.openButton.setText(_translate("DefaulKitManager", "Load"))
        self.cancelButton.setToolTip(_translate("DefaulKitManager", "Cancel this dialog"))
        self.cancelButton.setText(_translate("DefaulKitManager", "Cancel"))
