# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/GUI/insertMeasuresDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
QtGui.QPixmap = _CompatQPixmap


class Ui_InsertMeasuresDialog(object):
    def setupUi(self, InsertMeasuresDialog):
        InsertMeasuresDialog.setObjectName("InsertMeasuresDialog")
        InsertMeasuresDialog.resize(288, 281)
        self.verticalLayout = QtWidgets.QVBoxLayout(InsertMeasuresDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(InsertMeasuresDialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.numMeasuresSpinBox = QtWidgets.QSpinBox(InsertMeasuresDialog)
        self.numMeasuresSpinBox.setSuffix("")
        self.numMeasuresSpinBox.setMinimum(1)
        self.numMeasuresSpinBox.setMaximum(1000)
        self.numMeasuresSpinBox.setProperty("value", 1)
        self.numMeasuresSpinBox.setObjectName("numMeasuresSpinBox")
        self.gridLayout.addWidget(self.numMeasuresSpinBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(InsertMeasuresDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.beforeButton = QtWidgets.QRadioButton(InsertMeasuresDialog)
        self.beforeButton.setChecked(True)
        self.beforeButton.setObjectName("beforeButton")
        self.horizontalLayout.addWidget(self.beforeButton)
        self.afterButton = QtWidgets.QRadioButton(InsertMeasuresDialog)
        self.afterButton.setObjectName("afterButton")
        self.horizontalLayout.addWidget(self.afterButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.measureTabs = measureTabs(InsertMeasuresDialog)
        self.measureTabs.setObjectName("measureTabs")
        self.verticalLayout.addWidget(self.measureTabs)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(InsertMeasuresDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.numMeasuresSpinBox)
        self.label_3.setBuddy(self.beforeButton)

        self.retranslateUi(InsertMeasuresDialog)
        self.buttonBox.accepted.connect(InsertMeasuresDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(InsertMeasuresDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InsertMeasuresDialog)

    def retranslateUi(self, InsertMeasuresDialog):
        _translate = QtCore.QCoreApplication.translate
        InsertMeasuresDialog.setWindowTitle(_translate("InsertMeasuresDialog", "Insert Measures"))
        self.label.setToolTip(_translate("InsertMeasuresDialog", "Number of measures to insert"))
        self.label.setText(_translate("InsertMeasuresDialog", "Number of measures"))
        self.numMeasuresSpinBox.setToolTip(_translate("InsertMeasuresDialog", "Number of measures to insert"))
        self.label_3.setText(_translate("InsertMeasuresDialog", "Insert Measures..."))
        self.beforeButton.setToolTip(_translate("InsertMeasuresDialog", "Insert new measures before the current measure"))
        self.beforeButton.setText(_translate("InsertMeasuresDialog", "Before"))
        self.afterButton.setToolTip(_translate("InsertMeasuresDialog", "Insert new measures after the current measure"))
        self.afterButton.setText(_translate("InsertMeasuresDialog", "After"))
        self.measureTabs.setToolTip(_translate("InsertMeasuresDialog", "Select the count to use for the new measures"))
from Widgets.measureTabs import measureTabs
