# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/GUI/measurePropertiesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
QtGui.QPixmap = _CompatQPixmap


class Ui_measurePropertiesDialog(object):
    def setupUi(self, measurePropertiesDialog):
        measurePropertiesDialog.setObjectName("measurePropertiesDialog")
        measurePropertiesDialog.resize(352, 223)
        measurePropertiesDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(measurePropertiesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.measureTabs = measureTabs(measurePropertiesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measureTabs.sizePolicy().hasHeightForWidth())
        self.measureTabs.setSizePolicy(sizePolicy)
        self.measureTabs.setObjectName("measureTabs")
        self.horizontalLayout_2.addWidget(self.measureTabs)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(measurePropertiesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(measurePropertiesDialog)
        self.buttonBox.accepted.connect(measurePropertiesDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(measurePropertiesDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(measurePropertiesDialog)

    def retranslateUi(self, measurePropertiesDialog):
        _translate = QtCore.QCoreApplication.translate
        measurePropertiesDialog.setWindowTitle(_translate("measurePropertiesDialog", "Measure Properties"))
        self.measureTabs.setToolTip(_translate("measurePropertiesDialog", "Select the count for the measure"))
from Widgets.measureTabs import measureTabs
