# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\GUI\newScoreDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newScoreDialog(object):
    def setupUi(self, newScoreDialog):
        newScoreDialog.setObjectName("newScoreDialog")
        newScoreDialog.resize(680, 390)
        newScoreDialog.setMinimumSize(QtCore.QSize(620, 360))
        newScoreDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(newScoreDialog)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(newScoreDialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.numMeasuresSpinBox = QtWidgets.QSpinBox(newScoreDialog)
        self.numMeasuresSpinBox.setMinimum(1)
        self.numMeasuresSpinBox.setMaximum(100000)
        self.numMeasuresSpinBox.setProperty("value", 32)
        self.numMeasuresSpinBox.setObjectName("numMeasuresSpinBox")
        self.gridLayout.addWidget(self.numMeasuresSpinBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.measureTabs = measureTabs(newScoreDialog)
        self.measureTabs.setObjectName("measureTabs")
        self.verticalLayout.addWidget(self.measureTabs)
        self.label_2 = QtWidgets.QLabel(newScoreDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.kitCombobox = QtWidgets.QComboBox(newScoreDialog)
        self.kitCombobox.setObjectName("kitCombobox")
        self.verticalLayout.addWidget(self.kitCombobox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(newScoreDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.numMeasuresSpinBox)
        self.label_2.setBuddy(self.kitCombobox)

        self.retranslateUi(newScoreDialog)
        self.buttonBox.accepted.connect(newScoreDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(newScoreDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(newScoreDialog)
        newScoreDialog.setTabOrder(self.numMeasuresSpinBox, self.kitCombobox)
        newScoreDialog.setTabOrder(self.kitCombobox, self.buttonBox)

    def retranslateUi(self, newScoreDialog):
        _translate = QtCore.QCoreApplication.translate
        newScoreDialog.setWindowTitle(_translate("newScoreDialog", "New Score"))
        self.label.setToolTip(_translate("newScoreDialog", "The number of measures in the new score"))
        self.label.setText(_translate("newScoreDialog", "Number of measures"))
        self.numMeasuresSpinBox.setToolTip(_translate("newScoreDialog", "The number of measures in the new score"))
        self.numMeasuresSpinBox.setStatusTip(_translate("newScoreDialog", "The number of measures in the new score"))
        self.numMeasuresSpinBox.setSuffix(_translate("newScoreDialog", " measures"))
        self.measureTabs.setToolTip(_translate("newScoreDialog", "The default measure count for the new score"))
        self.label_2.setText(_translate("newScoreDialog", "Drum kit"))
from Widgets.measureTabs import measureTabs
