# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/GUI/versionDownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GUI.QtResourceCompat import QPixmap as _CompatQPixmap
QtGui.QPixmap = _CompatQPixmap


class Ui_VersionDownloader(object):
    def setupUi(self, VersionDownloader):
        VersionDownloader.setObjectName("VersionDownloader")
        VersionDownloader.setWindowModality(QtCore.Qt.ApplicationModal)
        VersionDownloader.resize(404, 151)
        self.verticalLayout = QtWidgets.QVBoxLayout(VersionDownloader)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message = QtWidgets.QLabel(VersionDownloader)
        self.message.setObjectName("message")
        self.verticalLayout.addWidget(self.message)
        self.resultBox = QtWidgets.QGroupBox(VersionDownloader)
        self.resultBox.setEnabled(False)
        self.resultBox.setObjectName("resultBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.resultBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resultLabel = QtWidgets.QLabel(self.resultBox)
        self.resultLabel.setText("")
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout_2.addWidget(self.resultLabel)
        self.verticalLayout.addWidget(self.resultBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(VersionDownloader)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(VersionDownloader)
        self.buttonBox.accepted.connect(VersionDownloader.accept) # type: ignore
        self.buttonBox.rejected.connect(VersionDownloader.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VersionDownloader)

    def retranslateUi(self, VersionDownloader):
        _translate = QtCore.QCoreApplication.translate
        VersionDownloader.setWindowTitle(_translate("VersionDownloader", "Finding new version information"))
        self.message.setText(_translate("VersionDownloader", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Contacting </span><a href=\"htttp://www.whatang.org\"><span style=\" text-decoration: underline; color:#0000ff;\">www.whatang.org</span></a><span style=\" font-size:8pt;\"> to detect latest version. Please wait...</span></p></body></html>"))
        self.resultBox.setTitle(_translate("VersionDownloader", "Result"))
