from PyQt5.QtGui import *  # noqa
from PyQt5.QtWidgets import *  # noqa
from PyQt5.QtPrintSupport import *  # noqa
from PyQt5.QtCore import QStandardPaths

class QDesktopServices:
    DocumentsLocation = QStandardPaths.DocumentsLocation
    HomeLocation = QStandardPaths.HomeLocation
    DesktopLocation = QStandardPaths.DesktopLocation
    MusicLocation = QStandardPaths.MusicLocation
    MoviesLocation = QStandardPaths.MoviesLocation
    PicturesLocation = QStandardPaths.PicturesLocation
    TempLocation = QStandardPaths.TempLocation

    @staticmethod
    def storageLocation(location):
        paths = QStandardPaths.standardLocations(location)
        if paths:
            return paths[0]
        return QStandardPaths.writableLocation(location)

# Compatibility for code generated by pyuic4
try:
    QApplication.UnicodeUTF8 = None
    _qt5_translate = QApplication.translate
    @staticmethod
    def _translate(context, sourceText, disambiguation=None, encoding=None):
        return _qt5_translate(context, sourceText, disambiguation)
    QApplication.translate = _translate
except Exception:
    pass

try:
    def _setMargin(self, margin):
        self.setContentsMargins(margin, margin, margin, margin)
    QLayout.setMargin = _setMargin
except Exception:
    pass
